# Generated by Django 4.2.5 on 2023-10-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stripe_product_id",
        ),
    ]
