# Generated by Django 4.2.5 on 2023-10-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
